name: Pre-Compiled and Upload

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          .\run-install.bat
          .\env\python.exe core.py prerequisites --pretraineds-hifigan --models --exe
      - name: Clean up unnecessary files
        run: |
          Remove-Item -Path 'LICENSE', 'run-tensorboard.sh', 'run-install.sh', 'run-applio.sh', 'run-install.bat', 'requirements.txt', '.gitignore', '.github', '.git' -Recurse -Force -ErrorAction SilentlyContinue
          Get-ChildItem -Path . -Include __pycache__ -Recurse -Directory | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue
      - name: Read version from config_template.json
        id: get-version
        run: |
          $version = (Get-Content -Path './assets/config_template.json' | ConvertFrom-Json).version
          echo "version=$version" >> $env:GITHUB_OUTPUT
      - name: Create ZIP file
        run: |
          $version = '${{ steps.get-version.outputs.version }}'
          Compress-Archive -Path 'D:\a\Applio\Applio\*' -DestinationPath "D:\a\Applio\ApplioV$version.zip"
      - name: Save Zip as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ApplioV${{ steps.get-version.outputs.version }}
          path: D:\a\Applio\ApplioV${{ steps.get-version.outputs.version }}.zip
